import cv2
img=cv2.imread("300mph.png",cv2.IMREAD_GRAYSCALE)
sobel_x=cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)
sobel_y=cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)
gauss=cv2.GaussianBlur(img,(5,5),0)
lap=cv2.Laplacian(img,cv2.CV_64F,ksize=3)
canny=cv2.Canny(img,100,200)
cv2.imshow("Original",img)
cv2.imshow("Sobel x",sobel_x)
cv2.imshow("Sobel y",sobel_y)
cv2.imshow("Gaussian Blur",gauss)
cv2.imshow("Laplacian",lap)
cv2.imshow("Canny",canny)
cv2.waitKey(0)
cv2.destroyAllWindows()